### ISSUE TITLE
5.4.0 crash

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#21]
AOSP 9
```
D Baresip Service: Received onStartCommand action Kill
D Baresip Service: 'stopped' from baresip or 'Kill' from MainActivity
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.tutpro.baresip, PID: 16850
E AndroidRuntime: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter view
E AndroidRuntime:        at com.tutpro.baresip.MainActivity$onCreate$3.onItemSelected(Unknown Source:7)
E AndroidRuntime:        at android.widget.AdapterView.fireOnSelected(AdapterView.java:944)
E AndroidRuntime:        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:933)
E AndroidRuntime:        at android.widget.AdapterView.selectionChanged(AdapterView.java:922)
E AndroidRuntime:        at android.widget.AdapterView.checkSelectionChanged(AdapterView.java:1105)
E AndroidRuntime:        at android.widget.AdapterView.handleDataChanged(AdapterView.java:1081)
E AndroidRuntime:        at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:191)
E AndroidRuntime:        at android.widget.Spinner.onMeasure(Spinner.java:602)
E AndroidRuntime:        at android.support.v7.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:420)
E AndroidRuntime:        at android.view.View.measure(View.java:23173)
E AndroidRuntime:        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
E AndroidRuntime:        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
E AndroidRuntime:        at android.view.View.measure(View.java:23173)
E AndroidRuntime:        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1308)
E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E AndroidRuntime:        at android.widget.ScrollView.onMeasure(ScrollView.java:350)
E AndroidRuntime:        at android.view.View.measure(View.java:23173)
E AndroidRuntime:        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
E AndroidRuntime:        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
E AndroidRuntime:        at android.view.View.measure(View.java:23173)
E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E AndroidRuntime:        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
E AndroidRuntime:        at android.view.View.measure(View.java:23173)
E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E AndroidRuntime:        at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
E AndroidRuntime:        at android.view.View.measure(View.java:23173)
E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E AndroidRuntime:        at android.view.View.measure(View.java:23173)
E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
E AndroidRuntime:        at android.view.View.measure(View.java:23173)
E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E AndroidRuntime:        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
E AndroidRuntime:        at android.view.View.measure(View.java:23173)
E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2736)
E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1590)
E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)
E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1478)
E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7362)
E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by juha-h** [comment]
What did you try to do when the crash happned?

**Comment by juha-h** [comment]
Which version of baresip? Had you already added an account when the
crash happened?  Can you repeat it? What does adb logcat tell?

**Comment by licaon-kter** [comment]
Happens at random, not sure what action.

Version is in title :)

Always have an account.

I can't repro at will.

That's from logcat.

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Happens at random, not sure what action.

So it does not happen when you Quit baresip?

In that case looks like Android is destroying baresip MainActivity,
which sends Kill intent to baresip service.

> That's from logcat.

What is in logcat before the crash?
``
D Baresip Service: Received onStartCommand action Kill
D Baresip Service: 'stopped' from baresip or 'Kill' from MainActivity
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
``

**Comment by licaon-kter** [comment]
> So it does not happen when you Quit baresip?

iirc, I've quit it then try to reopen it.

> What is in logcat before the crash?

Will see next time.

**Comment by juha-h** [comment]
I just pushed a commit that simplifies the quitting process and may help
to avoid the crash you have reported.  The new tag is 5.4.1.

**Comment by licaon-kter** [comment]
Seen it with 5.4.0 if I swipe the app away. I would expect it to stay in background since you have a notification going on.

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Seen it with 5.4.0 if I swipe the app away. I would expect it to stay
> in background since you have a notification going on.

In my 7.1 device, I don't have capability to "swipe the app away" or I
don't know how to do it.  If swiping away is same as pressing back
button, then baresip app pauses, becomes invisible, but stays alive.  If
I then press the app icon again, baresip resumes and becomes visible
again.

**Comment by licaon-kter** [comment]
:) press task manager button (the square one usually)...swipe away the card privew of your app...

**Comment by juha-h** [comment]
Licaon_Kter writes:

> :) press task manager button (the square one usually)...swipe away the
> card privew of your app...

OK, got it.  When I do it, 'adb logcat | grep baresip' shows:

``
02-26 21:15:35.044 14987 14987 D Baresip : Resumed
02-26 21:15:35.150 14987 14987 D Baresip : aorSpinner selecting 0
02-26 21:15:35.150 14987 14987 D Baresip : Setting sip:foo@test.tutpro.com current
02-26 21:15:35.150 14987 14987 D Baresip : running uag_current_set on 2477220168
02-26 21:15:43.258 14987 14987 D Baresip : Destroyed
``

And when I press baresip icon again, I get:

``
02-26 21:16:12.279 14987 14987 D Baresip : onCreate with intent action null
02-26 21:16:12.331 14987 14987 D Baresip : Resumed
02-26 21:16:12.428 14987 14987 D Baresip : aorSpinner selecting 0
02-26 21:15:35.150 14987 14987 D Baresip : Setting sip:foo@test.tutpro.com current
...
``

This is with 5.4.1 and it may very well explain, why it works for me:

``
- when main activity is destroyed, don't kill baresip service
  juha-h committed 3 hours ago
``

i.e., before 5.4.1, baresip service was indeed killed at main activity
destroy.

**Comment by juha-h** [comment]
Version 5.4.1 is now available on F-Droid.  Could you try with that (swiping/crash)?

**Comment by licaon-kter** [comment]
Looks fixed yeah, thanks.
