### ISSUE TITLE
App crashing immediatley when opened.

### ISSUE THREAD

**Issue by dankcatlord** [juha-h/baresip-studio#317]
This only seems to happen right after the app is installed and has no permissions.
```
type: crash
osVersion: google/bluejay/bluejay:13/TQ1A.230205.002/2023022300:user/release-keys
package: com.tutpro.baresip:254
process: com.tutpro.baresip
processUptime: 99 + 212 ms

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tutpro.baresip/com.tutpro.baresip.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property requestPermissionLauncher has not been initialized
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3783)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property requestPermissionLauncher has not been initialized
	at com.tutpro.baresip.MainActivity.startBaresip(MainActivity.kt:1625)
	at com.tutpro.baresip.MainActivity.onCreate(MainActivity.kt:675)
	at android.app.Activity.performCreate(Activity.java:8352)
	at android.app.Activity.performCreate(Activity.java:8331)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1422)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3627)
	... 14 more
```

**Comment by juha-h** [comment]
Thanks for the report.  Looks like you have Android version 13, which I don't have and didn't notice this crash.  Will be fixed in the next version.  You can before that avoid the crash by allowing Notifications permission in Android Setting before the first s

**Comment by juha-h** [comment]
Turned out that this issue most likely has already been fixed in the latest
master.  I created an APK from it:

https://box.tutpro.com/tmp/baresip.apk

Give it a try if you have time.  If you find something else not working
with Android 13, please let me know.  There is lots of

  if (Build.VERSION.SDK_INT >= 33)

tests in the code.  Android is a fast moving target.

**Comment by dankcatlord** [comment]
I tested it on my phone and it looks to be fixed

**Comment by juha-h** [comment]
dankcatlord writes:

> I tested it on my phone and it looks to be fixed

Thanks.
