### ISSUE TITLE
Handle Disabled Network Gracefully

### ISSUE THREAD

**Issue by githububub** [juha-h/baresip-studio#366]
When networking is disabled (e.g. only want to add an account w/o registration or to modify app settings) 55.2.0 and 56.0.0 crash instead of having the app launch to allow for  changes.

```
type: crash
osVersion: google/panther/panther:13/TQ2A.230505.002/2023050500:user/release-keys
package: com.tutpro.baresip:283
process: com.tutpro.baresip
processUptime: 302 + 196 ms

java.lang.RuntimeException: Unable to start service com.tutpro.baresip.BaresipService@1d20674 with Intent { act=Start cmp=com.tutpro.baresip/.BaresipService }: java.lang.NullPointerException: getNetworkInterfaces() must not be null
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4677)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.NullPointerException: getNetworkInterfaces() must not be null
	at com.tutpro.baresip.Utils.hotSpotAddresses(Utils.kt:433)
	at com.tutpro.baresip.BaresipService.onStartCommand(BaresipService.kt:426)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4659)
	... 11 more

```

**Comment by juha-h** [comment]
Tell what steps you did before the crash.  I just tested by starting baresip on device where no network was available and baresip gave notice "No network connection".  Then I created a new account and still no crash.  What did you do differently?

**Comment by juha-h** [comment]
Also (like should be done in all issues), give Android version of your device.  In getNetworkInterfaces() doc, I found this:

`ANDROID NOTE: On Android versions before S (API level 31), this method may throw a NullPointerException if called in an environment where there is a virtual interface without a parent interface present.`

Could it apply to you?

**Comment by juha-h** [comment]
Could you try with `https://box.tutpro.com/tmp/baresip.apk`.  Added catch of the null pointer exception.

**Comment by githububub** [comment]
Device is Pixel 7 running GrapheneOS A13. The above APK resolved the issue!
